[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "netdev"
version = "0.9.1"
description = "Asynchronous multi-vendor library for interacting with network devices"
authors = ["Sergey Yakovlev <selfuryon@gmail.com>"]
license = "Apache-2.0"
readme = "README.rst"
homepage = "https://netdev.readthedocs.io"
documentation = "https://netdev.readthedocs.io"
repository = "https://github.com/selfuryon/netdev"
keywords = ['netdev','network', 'netmiko', 'asyncio']
classifiers = [
        "Development Status :: 4 - Beta",
        "Framework :: AsyncIO",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Intended Audience :: Developers",
        "Intended Audience :: System Administrators",
        "Intended Audience :: Telecommunications Industry",
        "Topic :: System :: Networking",
        "Topic :: System :: Systems Administration",
]

[tool.poetry.dependencies]
python = "^3.6"
PyYAML = "^5.1"
asyncssh = "^1.15"
textfsm = "0.4.1"
sphinx = { version = "^2.0", optional = true}
sphinx_rtd_theme = { version = "^0.4", optional = true}

[tool.poetry.dev-dependencies]
PyYAML = "^5.1"
asyncssh = "^1.16"
textfsm = "^0.4"
black = {version = "^19.3b0",allows-prereleases = true}
pytest = "^4.0"
pylint = "^2.3"
sphinx = "^2.0"
sphinx_rtd_theme = "^0.4"

[tool.poetry.extras]
docs = ["sphinx", "sphinx_rtd_theme"]

